id: P010500
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS88389
  title: རྩིས་ཀྱི་ལག་ལེན་ཉེར་མཁོའི་བུམ་བཟང
  author: ''
  volumes:
    c883b4f2c8694baa8c2b2d2834c3d486:
      image_group_id: I1GS88391
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
