id: IDE11E74E
legacy_id: P010500
ocr_import_info:
  bdrc_scan_id: W1GS88389
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:33:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T21:08:46.844748+00:00'
last_modified: 2022-08-31 05:09:21.852215
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS88389
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS88389
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩིས་ཀྱི་ལག་ལེན་ཉེར་མཁོའི་བུམ་བཟང་།
  author: བོད་མཁས་པ་མི་ཕམ་དགེ་ལེགས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.5972097778902141
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1GS88391:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS88391
      total_pages: 474
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS88391.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5972097778902141
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
