id: IDE11E74E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:36:41+00:00'
last_modified: '2022-06-08T14:03:28.908126+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS88389
  title: རྩིས་ཀྱི་ལག་ལེན་ཉེར་མཁོའི་བུམ་བཟང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    987D:
      image_group_id: I1GS88391
      title: ''
      total_pages: 474
      order: 1
      base_file: 987D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
